# Generated by Django 2.1 on 2018-09-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(max_length=15, verbose_name='Tipo da Categoria'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='categoria',
            field=models.ForeignKey(choices=[('P', 'Pensamento'), ('O', 'Opinião'), ('C', 'Critica'), ('D', 'Duvida')], on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
    ]
