# Generated by Django 2.1 on 2018-09-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180919_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=25, verbose_name='Titulo do Grupo')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do grupo')),
                ('criador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ('tema',),
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('tipo',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
    ]
